// Cheat Wizard Trainer Runtime - standalone Windows x64 trainer template (no CRT/STL).
// cw-trainer-builder appends a validated Cheat Wizard trainer package to this PE.
// The runtime reads its own overlay, auto-attaches to the configured process,
// resolves redundant .cwptr / legacy .mcptr pointer chains by consensus, and exposes read/write/freeze.

using u8 = unsigned char; using u16 = unsigned short; using u32 = unsigned int; using u64 = unsigned long long;
using i16 = short; using i32 = int; using i64 = long long; using usize = unsigned long long; using uptr = unsigned long long;
using HANDLE=void*; using HINSTANCE=void*; using HWND=void*; using HDC=void*; using HBRUSH=void*; using HPEN=void*; using HFONT=void*; using HBITMAP=void*; using HGDIOBJ=void*; using HCURSOR=void*; using HICON=void*; using HMENU=void*;
using LPVOID=void*; using LPCVOID=const void*; using BOOL=int; using DWORD=unsigned long; using LONG=long; using UINT=unsigned int; using WPARAM=unsigned long long; using LPARAM=long long; using LRESULT=long long; using SIZE_T=unsigned long long; using ULONG_PTR=unsigned long long; using COLORREF=DWORD; using UINT_PTR=unsigned long long; using LPTHREAD_START_ROUTINE=DWORD (__stdcall *)(LPVOID);
#ifndef __stdcall
#define __stdcall
#endif

struct POINT_{LONG x,y;}; struct RECT_{LONG left,top,right,bottom;}; struct SIZE_{LONG cx,cy;};
struct MSG_{HWND hwnd;UINT message;WPARAM wParam;LPARAM lParam;DWORD time;POINT_ pt;DWORD lPrivate;};
struct PAINTSTRUCT_{HDC hdc;BOOL fErase;RECT_ rcPaint;BOOL fRestore;BOOL fIncUpdate;u8 rgbReserved[32];};
using WNDPROC_=LRESULT (__stdcall *)(HWND,UINT,WPARAM,LPARAM);
struct WNDCLASSEXA_{UINT cbSize;UINT style;WNDPROC_ lpfnWndProc;int cbClsExtra;int cbWndExtra;HINSTANCE hInstance;void* hIcon;HCURSOR hCursor;HBRUSH hbrBackground;const char* lpszMenuName;const char* lpszClassName;void* hIconSm;};
struct PROCESSENTRY32A_{DWORD dwSize,cntUsage,th32ProcessID;ULONG_PTR th32DefaultHeapID;DWORD th32ModuleID,cntThreads,th32ParentProcessID;LONG pcPriClassBase;DWORD dwFlags;char szExeFile[260];};
struct MODULEENTRY32W_{DWORD dwSize,th32ModuleID,th32ProcessID,GlblcntUsage,ProccntUsage;u8* modBaseAddr;DWORD modBaseSize;HANDLE hModule;wchar_t szModule[256];wchar_t szExePath[260];};
struct LARGE_INTEGER_{i64 QuadPart;};

extern "C" {
__declspec(dllimport) void __stdcall ExitProcess(u32); __declspec(dllimport) DWORD __stdcall GetLastError();
__declspec(dllimport) HANDLE __stdcall GetProcessHeap(); __declspec(dllimport) LPVOID __stdcall HeapAlloc(HANDLE,DWORD,SIZE_T); __declspec(dllimport) BOOL __stdcall HeapFree(HANDLE,DWORD,LPVOID);
__declspec(dllimport) HANDLE __stdcall CreateFileA(const char*,DWORD,DWORD,LPVOID,DWORD,DWORD,HANDLE); __declspec(dllimport) BOOL __stdcall ReadFile(HANDLE,LPVOID,DWORD,DWORD*,LPVOID); __declspec(dllimport) BOOL __stdcall CloseHandle(HANDLE); __declspec(dllimport) BOOL __stdcall GetFileSizeEx(HANDLE,LARGE_INTEGER_*); __declspec(dllimport) BOOL __stdcall SetFilePointerEx(HANDLE,LARGE_INTEGER_,LARGE_INTEGER_*,DWORD); __declspec(dllimport) DWORD __stdcall GetModuleFileNameA(HINSTANCE,char*,DWORD);
__declspec(dllimport) HANDLE __stdcall CreateToolhelp32Snapshot(DWORD,DWORD); __declspec(dllimport) BOOL __stdcall Process32First(HANDLE,LPVOID); __declspec(dllimport) BOOL __stdcall Process32Next(HANDLE,LPVOID); __declspec(dllimport) BOOL __stdcall Module32FirstW(HANDLE,LPVOID); __declspec(dllimport) BOOL __stdcall Module32NextW(HANDLE,LPVOID);
__declspec(dllimport) HANDLE __stdcall OpenProcess(DWORD,BOOL,DWORD); __declspec(dllimport) BOOL __stdcall IsWow64Process(HANDLE,BOOL*); __declspec(dllimport) BOOL __stdcall ReadProcessMemory(HANDLE,LPCVOID,LPVOID,SIZE_T,SIZE_T*); __declspec(dllimport) BOOL __stdcall WriteProcessMemory(HANDLE,LPVOID,LPCVOID,SIZE_T,SIZE_T*);
__declspec(dllimport) HANDLE __stdcall CreateThread(LPVOID,SIZE_T,LPTHREAD_START_ROUTINE,LPVOID,DWORD,DWORD*); __declspec(dllimport) void __stdcall Sleep(DWORD);
__declspec(dllimport) HINSTANCE __stdcall GetModuleHandleA(const char*); __declspec(dllimport) HINSTANCE __stdcall LoadLibraryA(const char*); __declspec(dllimport) void* __stdcall GetProcAddress(HINSTANCE,const char*);
__declspec(dllimport) u16 __stdcall RegisterClassExA(const WNDCLASSEXA_*); __declspec(dllimport) HWND __stdcall CreateWindowExA(DWORD,const char*,const char*,DWORD,int,int,int,int,HWND,HMENU,HINSTANCE,LPVOID); __declspec(dllimport) LRESULT __stdcall DefWindowProcA(HWND,UINT,WPARAM,LPARAM); __declspec(dllimport) BOOL __stdcall ShowWindow(HWND,int); __declspec(dllimport) BOOL __stdcall UpdateWindow(HWND); __declspec(dllimport) BOOL __stdcall GetMessageA(MSG_*,HWND,UINT,UINT); __declspec(dllimport) BOOL __stdcall TranslateMessage(const MSG_*); __declspec(dllimport) LRESULT __stdcall DispatchMessageA(const MSG_*); __declspec(dllimport) void __stdcall PostQuitMessage(int); __declspec(dllimport) UINT_PTR __stdcall SetTimer(HWND,UINT_PTR,UINT,void*); __declspec(dllimport) BOOL __stdcall KillTimer(HWND,UINT_PTR); __declspec(dllimport) HDC __stdcall BeginPaint(HWND,PAINTSTRUCT_*); __declspec(dllimport) BOOL __stdcall EndPaint(HWND,const PAINTSTRUCT_*); __declspec(dllimport) BOOL __stdcall InvalidateRect(HWND,const RECT_*,BOOL); __declspec(dllimport) BOOL __stdcall GetClientRect(HWND,RECT_*); __declspec(dllimport) int __stdcall MessageBoxA(HWND,const char*,const char*,UINT); __declspec(dllimport) HCURSOR __stdcall LoadCursorA(HINSTANCE,const char*); __declspec(dllimport) HICON __stdcall LoadIconA(HINSTANCE,const char*); __declspec(dllimport) short __stdcall GetKeyState(int); __declspec(dllimport) BOOL __stdcall SetProcessDPIAware();
__declspec(dllimport) int __stdcall FillRect(HDC,const RECT_*,HBRUSH); __declspec(dllimport) int __stdcall FrameRect(HDC,const RECT_*,HBRUSH); __declspec(dllimport) int __stdcall DrawTextA(HDC,const char*,int,RECT_*,UINT);
__declspec(dllimport) BOOL __stdcall GetTextExtentPoint32A(HDC,const char*,int,SIZE_*); __declspec(dllimport) HBRUSH __stdcall CreateSolidBrush(COLORREF); __declspec(dllimport) HPEN __stdcall CreatePen(int,int,COLORREF); __declspec(dllimport) BOOL __stdcall DeleteObject(HGDIOBJ); __declspec(dllimport) HGDIOBJ __stdcall SelectObject(HDC,HGDIOBJ); __declspec(dllimport) HFONT __stdcall CreateFontA(int,int,int,int,int,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD,DWORD,const char*); __declspec(dllimport) BOOL __stdcall RoundRect(HDC,int,int,int,int,int,int); __declspec(dllimport) BOOL __stdcall MoveToEx(HDC,int,int,POINT_*); __declspec(dllimport) BOOL __stdcall LineTo(HDC,int,int); __declspec(dllimport) COLORREF __stdcall SetTextColor(HDC,COLORREF); __declspec(dllimport) COLORREF __stdcall SetBkColor(HDC,COLORREF); __declspec(dllimport) int __stdcall SetBkMode(HDC,int); __declspec(dllimport) HDC __stdcall CreateCompatibleDC(HDC); __declspec(dllimport) HBITMAP __stdcall CreateCompatibleBitmap(HDC,int,int); __declspec(dllimport) BOOL __stdcall DeleteDC(HDC); __declspec(dllimport) BOOL __stdcall BitBlt(HDC,int,int,int,int,HDC,int,int,DWORD);
}
extern "C" int _fltused=0; extern "C" void* memcpy(void* d,const void* s,usize n){auto* a=(u8*)d;auto* b=(const u8*)s;for(usize i=0;i<n;++i)a[i]=b[i];return d;} extern "C" void* memset(void* d,int c,usize n){auto* a=(u8*)d;for(usize i=0;i<n;++i)a[i]=(u8)c;return d;}

static constexpr DWORD GENERIC_READ=0x80000000UL,GENERIC_WRITE=0x40000000UL,OPEN_EXISTING=3,FILE_ATTRIBUTE_NORMAL=0x80,FILE_BEGIN=0;
static constexpr DWORD TH32CS_SNAPPROCESS=2,TH32CS_SNAPMODULE=8,TH32CS_SNAPMODULE32=0x10; static constexpr DWORD PROCESS_VM_OPERATION=8,PROCESS_VM_READ=0x10,PROCESS_VM_WRITE=0x20,PROCESS_QUERY_INFORMATION=0x400;
static constexpr DWORD WS_OVERLAPPED=0,WS_CAPTION=0x00C00000L,WS_SYSMENU=0x00080000L,WS_MINIMIZEBOX=0x00020000L,WS_THICKFRAME=0x00040000L,WS_MAXIMIZEBOX=0x00010000L; static constexpr int SW_SHOW=5; static constexpr UINT WM_CREATE=1,WM_DESTROY=2,WM_PAINT=15,WM_CLOSE=16,WM_KEYDOWN=0x100,WM_CHAR=0x102,WM_TIMER=0x113,WM_MOUSEMOVE=0x200,WM_LBUTTONDOWN=0x201,WM_LBUTTONDBLCLK=0x203; static constexpr UINT CS_DBLCLKS=8; static constexpr UINT MB_OK=0,MB_ICONERROR=0x10;
static constexpr UINT DT_LEFT=0,DT_CENTER=1,DT_VCENTER=4,DT_SINGLELINE=0x20,DT_END_ELLIPSIS=0x8000,DT_WORDBREAK=0x10; static constexpr int TRANSPARENT=1,PS_SOLID=0; static constexpr DWORD SRCCOPY=0x00CC0020; static constexpr int FW_NORMAL=400,FW_SEMIBOLD=600,CLEARTYPE_QUALITY=5;
static constexpr uptr INVALID_HANDLE_BITS=~(uptr)0;
static constexpr usize MAX_ENTRIES=8,MAX_LAYOUT=32,MAX_CHAINS=100000,MAX_DEPTH=64,MAX_MODULES=256;

static usize slen(const char* s){usize n=0;if(s)while(s[n])++n;return n;} static bool seq(const char*a,const char*b){if(!a||!b)return false;while(*a&&*b){if(*a++!=*b++)return false;}return *a==*b;} static char lowerc(char c){return c>='A'&&c<='Z'?(char)(c+32):c;} static bool sieq(const char*a,const char*b){if(!a||!b)return false;while(*a&&*b){if(lowerc(*a++)!=lowerc(*b++))return false;}return *a==*b;} static void scopy(char*d,usize cap,const char*s){if(!cap)return;usize i=0;if(s)for(;i+1<cap&&s[i];++i)d[i]=s[i];d[i]=0;} static void zero(void*p,usize n){memset(p,0,n);} static bool addoff(uptr base,i64 off,uptr& out){if(off>=0){uptr x=(uptr)off;if(~(uptr)0-base<x)return false;out=base+x;return true;}u64 m=(u64)(-(off+1))+1ULL;if(base<(uptr)m)return false;out=base-(uptr)m;return true;}
static COLORREF rgb(u8 r,u8 g,u8 b){return (DWORD)r|((DWORD)g<<8)|((DWORD)b<<16);} static void appendc(char*b,usize cap,usize&n,char c){if(n+1<cap)b[n++]=c;} static void appends(char*b,usize cap,usize&n,const char*s){if(!s)return;while(*s&&n+1<cap)b[n++]=*s++;} static void appendu(char*b,usize cap,usize&n,u64 v){char t[32];int k=0;if(!v)t[k++]='0';while(v&&k<31){t[k++]=(char)('0'+v%10);v/=10;}while(k--)appendc(b,cap,n,t[k]);} static void appendi(char*b,usize cap,usize&n,i64 v){if(v<0){appendc(b,cap,n,'-');u64 m=(u64)(-(v+1))+1ULL;appendu(b,cap,n,m);}else appendu(b,cap,n,(u64)v);} static void appendhex(char*b,usize cap,usize&n,uptr v){appends(b,cap,n,"0x");const char*h="0123456789ABCDEF";bool started=false;for(int s=60;s>=0;s-=4){u8 d=(u8)((v>>s)&15);if(d||started||s==0){started=true;appendc(b,cap,n,h[d]);}}} static void appenddouble(char*b,usize cap,usize&n,double v){if(v<0){appendc(b,cap,n,'-');v=-v;}u64 w=(u64)v;appendu(b,cap,n,w);appendc(b,cap,n,'.');double f=v-(double)w;for(int i=0;i<4;++i){f*=10;int d=(int)f;if(d<0)d=0;if(d>9)d=9;appendc(b,cap,n,(char)('0'+d));f-=d;}}
static bool parsei(const char*s,i64&out){if(!s||!*s)return false;bool neg=false;if(*s=='-'||*s=='+'){neg=*s=='-';++s;}if(!*s)return false;u64 v=0;while(*s){if(*s<'0'||*s>'9')return false;u64 d=(u64)(*s-'0');if(v>(0x7FFFFFFFFFFFFFFFULL+d)/10ULL)return false;v=v*10+d;++s;}if(neg){if(v>0x8000000000000000ULL)return false;out=v==0x8000000000000000ULL?(-9223372036854775807LL-1):-(i64)v;}else{if(v>0x7FFFFFFFFFFFFFFFULL)return false;out=(i64)v;}return true;} static bool parsed(const char*s,double&out){if(!s||!*s)return false;bool neg=false;if(*s=='-'||*s=='+'){neg=*s=='-';++s;}double v=0;bool any=false;while(*s>='0'&&*s<='9'){v=v*10+(*s-'0');++s;any=true;}if(*s=='.'){++s;double p=.1;while(*s>='0'&&*s<='9'){v+=(*s-'0')*p;p*=.1;++s;any=true;}}if(!any||*s)return false;out=neg?-v:v;return true;}

enum class ValueType:u8{Byte,Int16,Int32,Int64,Float,Double,Mixed,Invalid}; static u8 tsize(ValueType t){switch(t){case ValueType::Byte:return 1;case ValueType::Int16:return 2;case ValueType::Int32:return 4;case ValueType::Int64:return 8;case ValueType::Float:return 4;case ValueType::Double:return 8;default:return 0;}} static const char*tname(ValueType t){switch(t){case ValueType::Byte:return"Byte";case ValueType::Int16:return"Int16";case ValueType::Int32:return"Int32";case ValueType::Int64:return"Int64";case ValueType::Float:return"Float";case ValueType::Double:return"Double";default:return"?";}}
static bool encode(ValueType t,const char*s,u8 out[8]){zero(out,8);i64 iv=0;double dv=0;switch(t){case ValueType::Byte:if(!parsei(s,iv)||iv<0||iv>255)return false;out[0]=(u8)iv;return true;case ValueType::Int16:if(!parsei(s,iv)||iv<-32768||iv>32767)return false;{i16 x=(i16)iv;memcpy(out,&x,2);}return true;case ValueType::Int32:if(!parsei(s,iv)||iv<(-2147483647LL-1)||iv>2147483647LL)return false;{i32 x=(i32)iv;memcpy(out,&x,4);}return true;case ValueType::Int64:if(!parsei(s,iv))return false;memcpy(out,&iv,8);return true;case ValueType::Float:if(!parsed(s,dv))return false;{float x=(float)dv;memcpy(out,&x,4);}return true;case ValueType::Double:if(!parsed(s,dv))return false;memcpy(out,&dv,8);return true;default:return false;}}
static void formatv(char*b,usize cap,ValueType t,const u8*raw){usize n=0;switch(t){case ValueType::Byte:appendu(b,cap,n,raw[0]);break;case ValueType::Int16:{i16 x;memcpy(&x,raw,2);appendi(b,cap,n,x);}break;case ValueType::Int32:{i32 x;memcpy(&x,raw,4);appendi(b,cap,n,x);}break;case ValueType::Int64:{i64 x;memcpy(&x,raw,8);appendi(b,cap,n,x);}break;case ValueType::Float:{float x;memcpy(&x,raw,4);appenddouble(b,cap,n,x);}break;case ValueType::Double:{double x;memcpy(&x,raw,8);appenddouble(b,cap,n,x);}break;default:appends(b,cap,n,"?");}b[n]=0;}

struct Module{uptr base;u64 size;char name[256];}; struct Chain{char module[256];uptr root;i64* offsets;u32 depth;};
enum LayoutType:u8{LayoutTitle=0,LayoutSubtitle=1,LayoutField=2};
struct Entry{char id[64],label[128],def[64];bool showCurrent,allowWrite,allowFreeze;ValueType type;usize pointerSize;Chain* chains;usize chainCount;uptr resolved;usize agree,resolvedCount;bool valid;char edit[64];bool freeze;u8 freezeBytes[8];};
struct LayoutItem{u8 type;u32 entryIndex;char text[192];};
struct App{char title[128];char process[260];Entry entries[MAX_ENTRIES];usize entryCount;LayoutItem layout[MAX_LAYOUT];usize layoutCount;u32 width,height;COLORREF bg,panel,surface,accent,text,muted;}; static App g_app{}; static HANDLE g_heap=nullptr,g_proc=nullptr;static DWORD g_pid=0;static usize g_ptrSize=8;static Module g_mods[MAX_MODULES];static usize g_modCount=0;static volatile LONG g_stop=0; static HWND g_hwnd=nullptr;static int g_focus=-1;static usize g_cursor=0,g_anchor=0;static char g_status[256]="Waiting for process...";

static u32 crc32(const u8* p,usize n){u32 c=0xFFFFFFFFu;for(usize i=0;i<n;++i){c^=p[i];for(int j=0;j<8;++j)c=(c>>1)^(0xEDB88320u&((u32)-(i32)(c&1)));}return ~c;}
static bool rd16(const u8*&p,const u8*e,u16&v){if((usize)(e-p)<2)return false;v=(u16)p[0]|((u16)p[1]<<8);p+=2;return true;} static bool rd32(const u8*&p,const u8*e,u32&v){if((usize)(e-p)<4)return false;v=(u32)p[0]|((u32)p[1]<<8)|((u32)p[2]<<16)|((u32)p[3]<<24);p+=4;return true;} static bool rd64(const u8*&p,const u8*e,u64&v){if((usize)(e-p)<8)return false;v=0;for(int i=0;i<8;++i)v|=(u64)p[i]<<(i*8);p+=8;return true;} static bool take(const u8*&p,const u8*e,void*d,usize n){if((usize)(e-p)<n)return false;memcpy(d,p,n);p+=n;return true;}
static bool parse_profile(const u8*data,usize size,Entry&en){const u8*p=data,*e=data+size;const char magic[8]={'C','W','P','R','O','F','0','1'},legacy[8]={'M','C','E','P','R','O','F','1'};if(size<32)return false;bool magicOk=true,legacyOk=true;for(int i=0;i<8;++i){if(data[i]!=(u8)magic[i])magicOk=false;if(data[i]!=(u8)legacy[i])legacyOk=false;}if(!magicOk&&!legacyOk)return false;p+=8;u32 ver=0,ps=0,tc=0;u16 procLen=0;u64 cc=0;if(!rd32(p,e,ver)||!rd32(p,e,ps)||!rd32(p,e,tc)||!rd16(p,e,procLen)||!rd64(p,e,cc))return false;if(ver!=1||(ps!=4&&ps!=8)||tc>5||!cc||cc>MAX_CHAINS||procLen>4096||(usize)(e-p)<procLen)return false;p+=procLen;en.pointerSize=ps;en.type=(ValueType)tc;en.chainCount=(usize)cc;en.chains=(Chain*)HeapAlloc(g_heap,0,en.chainCount*sizeof(Chain));if(!en.chains)return false;zero(en.chains,en.chainCount*sizeof(Chain));for(usize i=0;i<en.chainCount;++i){u16 ml=0;u64 root=0;u32 depth=0;if(!rd16(p,e,ml)||!ml||ml>=256||(usize)(e-p)<ml){return false;}for(u16 j=0;j<ml;++j)en.chains[i].module[j]=(char)*p++;en.chains[i].module[ml]=0;if(!rd64(p,e,root)||!rd32(p,e,depth)||!depth||depth>MAX_DEPTH)return false;en.chains[i].root=(uptr)root;en.chains[i].depth=depth;en.chains[i].offsets=(i64*)HeapAlloc(g_heap,0,(usize)depth*sizeof(i64));if(!en.chains[i].offsets)return false;for(u32 j=0;j<depth;++j){u64 raw=0;if(!rd64(p,e,raw))return false;memcpy(&en.chains[i].offsets[j],&raw,8);}}return p==e;}

static bool load_package(){
 char path[1024]{};DWORD n=GetModuleFileNameA(nullptr,path,(DWORD)sizeof(path));if(!n||n>=sizeof(path))return false;
 g_app.bg=rgb(9,9,11);g_app.panel=rgb(24,24,27);g_app.surface=rgb(39,39,42);g_app.accent=rgb(37,99,235);g_app.text=rgb(250,250,250);g_app.muted=rgb(161,161,170);
 HANDLE f=CreateFileA(path,GENERIC_READ,1|2,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if(f==(HANDLE)INVALID_HANDLE_BITS)return false;LARGE_INTEGER_ sz{};if(!GetFileSizeEx(f,&sz)||sz.QuadPart<40){CloseHandle(f);return false;}
 struct Footer{char magic[8];u32 version,reserved;u64 off,size;u32 crc,reserved2;}ft{};LARGE_INTEGER_ pos{sz.QuadPart-(i64)sizeof(ft)};if(!SetFilePointerEx(f,pos,nullptr,FILE_BEGIN)){CloseHandle(f);return false;}DWORD got=0;if(!ReadFile(f,&ft,(DWORD)sizeof(ft),&got,nullptr)||got!=sizeof(ft)){CloseHandle(f);return false;}const char fm[8]={'C','W','T','R','F','T','R','1'},legacyFm[8]={'M','C','T','R','F','T','R','1'};bool footerOk=true,legacyFooterOk=true;for(int i=0;i<8;++i){if(ft.magic[i]!=fm[i])footerOk=false;if(ft.magic[i]!=legacyFm[i])legacyFooterOk=false;}if(!footerOk&&!legacyFooterOk){CloseHandle(f);return false;}if((ft.version<1||ft.version>3)||ft.off+ft.size+(u64)sizeof(ft)!=(u64)sz.QuadPart||ft.size>64ULL*1024*1024){CloseHandle(f);return false;}
 u8*pkg=(u8*)HeapAlloc(g_heap,0,(usize)ft.size);if(!pkg){CloseHandle(f);return false;}pos.QuadPart=(i64)ft.off;SetFilePointerEx(f,pos,nullptr,FILE_BEGIN);got=0;bool ok=ReadFile(f,pkg,(DWORD)ft.size,&got,nullptr)&&got==(DWORD)ft.size&&crc32(pkg,(usize)ft.size)==ft.crc;CloseHandle(f);if(!ok){HeapFree(g_heap,0,pkg);return false;}
 const u8*p=pkg,*e=pkg+ft.size;const char pm[8]={'C','W','T','R','P','K','G','1'},legacyPm[8]={'M','C','T','R','P','K','G','1'};if((usize)(e-p)<8){HeapFree(g_heap,0,pkg);return false;}bool packageOk=true,legacyPackageOk=true;for(int i=0;i<8;++i){if(p[i]!=(u8)pm[i])packageOk=false;if(p[i]!=(u8)legacyPm[i])legacyPackageOk=false;}if(!packageOk&&!legacyPackageOk){HeapFree(g_heap,0,pkg);return false;}p+=8;u32 ver=0,ec=0,tl=0,pl=0,w=0,h=0,lc=0;if(!rd32(p,e,ver)||!rd32(p,e,ec)||!rd32(p,e,tl)||!rd32(p,e,pl)||!rd32(p,e,w)||!rd32(p,e,h)||(ver<1||ver>3)||!ec||ec>MAX_ENTRIES||tl>=sizeof(g_app.title)||pl>=sizeof(g_app.process)){HeapFree(g_heap,0,pkg);return false;}
 if(ver>=2){u32 c=0;if(!rd32(p,e,c)){ok=false;}else g_app.bg=(COLORREF)c;if(ok&&!rd32(p,e,c))ok=false;else if(ok)g_app.panel=(COLORREF)c;if(ok&&!rd32(p,e,c))ok=false;else if(ok)g_app.surface=(COLORREF)c;if(ok&&!rd32(p,e,c))ok=false;else if(ok)g_app.accent=(COLORREF)c;if(ok&&!rd32(p,e,c))ok=false;else if(ok)g_app.text=(COLORREF)c;if(ok&&!rd32(p,e,c))ok=false;else if(ok)g_app.muted=(COLORREF)c;if(!ok){HeapFree(g_heap,0,pkg);return false;}}
 if(ver>=3){if(!rd32(p,e,lc)||!lc||lc>MAX_LAYOUT){HeapFree(g_heap,0,pkg);return false;}}
 if(!take(p,e,g_app.title,tl)||!take(p,e,g_app.process,pl)){HeapFree(g_heap,0,pkg);return false;}g_app.title[tl]=0;g_app.process[pl]=0;g_app.width=w?w:620;g_app.height=h?h:460;g_app.entryCount=ec;
 for(u32 i=0;i<ec;++i){Entry&x=g_app.entries[i];u32 il=0,ll=0,dl=0,flags=0;u64 prof=0;if(!rd32(p,e,il)||!rd32(p,e,ll)||!rd32(p,e,dl)||!rd32(p,e,flags)||!rd64(p,e,prof)||il>=sizeof(x.id)||ll>=sizeof(x.label)||dl>=sizeof(x.def)||prof>16ULL*1024*1024||(usize)(e-p)<il+ll+dl+(usize)prof){ok=false;break;}take(p,e,x.id,il);x.id[il]=0;take(p,e,x.label,ll);x.label[ll]=0;take(p,e,x.def,dl);x.def[dl]=0;x.showCurrent=(flags&1)!=0;x.allowWrite=(flags&2)!=0;x.allowFreeze=(flags&4)!=0;const u8*pd=p;p+=(usize)prof;if(!parse_profile(pd,(usize)prof,x)){ok=false;break;}scopy(x.edit,sizeof(x.edit),x.def);}
 if(ok&&ver>=3){bool used[MAX_ENTRIES]{};g_app.layoutCount=lc;for(u32 i=0;i<lc;++i){LayoutItem&li=g_app.layout[i];u32 type=0,entryIndex=0,textLen=0;if(!rd32(p,e,type)||!rd32(p,e,entryIndex)||!rd32(p,e,textLen)||type>LayoutField||textLen>=sizeof(li.text)||(usize)(e-p)<textLen){ok=false;break;}li.type=(u8)type;li.entryIndex=entryIndex;if(textLen){take(p,e,li.text,textLen);li.text[textLen]=0;}if(li.type==LayoutField){if(entryIndex>=ec||textLen||used[entryIndex]){ok=false;break;}used[entryIndex]=true;}else if(entryIndex!=0xFFFFFFFFu||!textLen){ok=false;break;}}if(ok)for(u32 i=0;i<ec;++i)if(!used[i]){ok=false;break;}}
 else if(ok){g_app.layoutCount=ec;for(u32 i=0;i<ec;++i){g_app.layout[i].type=LayoutField;g_app.layout[i].entryIndex=i;g_app.layout[i].text[0]=0;}}
 HeapFree(g_heap,0,pkg);return ok&&p==e;
}

static bool refresh_modules(){g_modCount=0;if(!g_pid)return false;HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPMODULE|TH32CS_SNAPMODULE32,g_pid);if(s==(HANDLE)INVALID_HANDLE_BITS)return false;MODULEENTRY32W_ m{};m.dwSize=(DWORD)sizeof(m);if(!Module32FirstW(s,&m)){CloseHandle(s);return false;}do{if(g_modCount>=MAX_MODULES)break;Module&d=g_mods[g_modCount++];d.base=(uptr)m.modBaseAddr;d.size=m.modBaseSize;usize j=0;while(j+1<sizeof(d.name)&&m.szModule[j]){wchar_t wc=m.szModule[j];d.name[j]=(char)(wc<128?wc:'?');++j;}d.name[j]=0;}while(Module32NextW(s,&m));CloseHandle(s);return g_modCount>0;} static int modindex(const char*n){for(usize i=0;i<g_modCount;++i)if(sieq(g_mods[i].name,n))return(int)i;return-1;}
static bool readptr(uptr a,uptr&v){SIZE_T got=0;if(g_ptrSize==4){u32 x=0;if(!ReadProcessMemory(g_proc,(LPCVOID)a,&x,4,&got)||got!=4)return false;v=x;return true;}u64 x=0;if(!ReadProcessMemory(g_proc,(LPCVOID)a,&x,8,&got)||got!=8)return false;v=x;return true;}
static bool resolve_chain(const Chain&c,uptr&out){int mi=modindex(c.module);if(mi<0)return false;uptr a=g_mods[mi].base+c.root;for(u32 i=0;i<c.depth;++i){uptr pv=0;if(!readptr(a,pv)||!addoff(pv,c.offsets[i],a))return false;}out=a;return true;}
static void sortup(uptr*a,usize n){for(usize i=1;i<n;++i){uptr v=a[i];usize j=i;while(j&&a[j-1]>v){a[j]=a[j-1];--j;}a[j]=v;}}
static bool resolve_entry(Entry&x){x.valid=false;x.agree=x.resolvedCount=0;x.resolved=0;if(!g_proc||x.pointerSize!=g_ptrSize||!x.chainCount)return false;uptr*vals=(uptr*)HeapAlloc(g_heap,0,x.chainCount*sizeof(uptr));if(!vals)return false;for(usize i=0;i<x.chainCount;++i){uptr r=0;if(resolve_chain(x.chains[i],r))vals[x.resolvedCount++]=r;}if(!x.resolvedCount){HeapFree(g_heap,0,vals);return false;}sortup(vals,x.resolvedCount);uptr best=vals[0];usize bestc=1,run=1;for(usize i=1;i<x.resolvedCount;++i){if(vals[i]==vals[i-1])++run;else{if(run>bestc){bestc=run;best=vals[i-1];}run=1;}}if(run>bestc){bestc=run;best=vals[x.resolvedCount-1];}HeapFree(g_heap,0,vals);x.resolved=best;x.agree=bestc;x.valid=bestc*2>x.resolvedCount;return x.valid;}
static bool readentry(Entry&x,u8 raw[8]){if(!x.valid&&!resolve_entry(x))return false;SIZE_T got=0;u8 z=tsize(x.type);return z&&ReadProcessMemory(g_proc,(LPCVOID)x.resolved,raw,z,&got)&&got==z;} static bool writeentry(Entry&x,const char*text){u8 raw[8]{};if(!x.allowWrite||!x.valid||!encode(x.type,text,raw))return false;SIZE_T wrote=0;u8 z=tsize(x.type);return WriteProcessMemory(g_proc,(LPVOID)x.resolved,raw,z,&wrote)&&wrote==z;}

static bool find_process(){HANDLE s=CreateToolhelp32Snapshot(TH32CS_SNAPPROCESS,0);if(s==(HANDLE)INVALID_HANDLE_BITS)return false;PROCESSENTRY32A_ pe{};pe.dwSize=(DWORD)sizeof(pe);DWORD found=0;if(Process32First(s,&pe)){do{if(sieq(pe.szExeFile,g_app.process)){found=pe.th32ProcessID;break;}}while(Process32Next(s,&pe));}CloseHandle(s);if(!found)return false;if(found==g_pid&&g_proc)return true;if(g_proc){CloseHandle(g_proc);g_proc=nullptr;}g_proc=OpenProcess(PROCESS_QUERY_INFORMATION|PROCESS_VM_READ|PROCESS_VM_WRITE|PROCESS_VM_OPERATION,0,found);if(!g_proc){g_pid=0;return false;}g_pid=found;BOOL wow=0;IsWow64Process(g_proc,&wow);g_ptrSize=wow?4:8;refresh_modules();for(usize i=0;i<g_app.entryCount;++i){g_app.entries[i].valid=false;g_app.entries[i].freeze=false;resolve_entry(g_app.entries[i]);}return true;}
static void detach(){if(g_proc)CloseHandle(g_proc);g_proc=nullptr;g_pid=0;g_modCount=0;for(usize i=0;i<g_app.entryCount;++i){g_app.entries[i].valid=false;g_app.entries[i].freeze=false;}}
static DWORD __stdcall freeze_thread(LPVOID){while(!g_stop){HANDLE p=g_proc;if(p){for(usize i=0;i<g_app.entryCount;++i){Entry&x=g_app.entries[i];if(!x.freeze||!x.valid)continue;SIZE_T wr=0;u8 z=tsize(x.type);WriteProcessMemory(p,(LPVOID)x.resolved,x.freezeBytes,z,&wr);}}Sleep(10);}return 0;}

struct R{int x,y,w,h;};static bool inside(R r,int x,int y){return x>=r.x&&x<r.x+r.w&&y>=r.y&&y<r.y+r.h;} static RECT_ rr(R r){return RECT_{r.x,r.y,r.x+r.w,r.y+r.h};}
static HBRUSH bBg,bPanel,bSurf,bHover,bAccent,bGood,bWarn,bSelect;static HPEN pBorder,pAccent;static HFONT fNorm,fSmall,fBold,fTitle,fMono;static COLORREF Z950,Z900,Z800,Z700,Z400,Z50,BLUE,GREEN=0x93D69A,AMBER=0x24BFFB;static int mouseX=-1,mouseY=-1;
static COLORREF mixc(COLORREF a,COLORREF b,int wa){int wb=100-wa;u8 ar=(u8)(a&255),ag=(u8)((a>>8)&255),ab=(u8)((a>>16)&255),br=(u8)(b&255),bg=(u8)((b>>8)&255),bb=(u8)((b>>16)&255);return rgb((u8)((ar*wa+br*wb)/100),(u8)((ag*wa+bg*wb)/100),(u8)((ab*wa+bb*wb)/100));}
static void text(HDC dc,const char*s,R r,COLORREF c,HFONT f,UINT fl){RECT_ q=rr(r);SetBkMode(dc,TRANSPARENT);SetTextColor(dc,c);SelectObject(dc,(HGDIOBJ)f);DrawTextA(dc,s,-1,&q,fl);} static void box(HDC dc,R r,HBRUSH b,HPEN p,int rad=8){HGDIOBJ ob=SelectObject(dc,(HGDIOBJ)b),op=SelectObject(dc,(HGDIOBJ)p);RoundRect(dc,r.x,r.y,r.x+r.w,r.y+r.h,rad,rad);SelectObject(dc,op);SelectObject(dc,ob);} static void button(HDC dc,R r,const char*s,bool enabled=true,bool primary=false){bool h=enabled&&inside(r,mouseX,mouseY);HBRUSH br=primary&&enabled?bAccent:(h?bHover:bSurf);box(dc,r,br,pBorder,8);text(dc,s,r,enabled?Z50:Z700,fBold,DT_CENTER|DT_VCENTER|DT_SINGLELINE);}
static int textw(HDC dc,HFONT f,const char*s,usize n){if(!s||!n)return 0;HGDIOBJ old=SelectObject(dc,(HGDIOBJ)f);SIZE_ z{};BOOL ok=GetTextExtentPoint32A(dc,s,(int)n,&z);SelectObject(dc,old);return ok?(int)z.cx:0;}
static usize caret_from_x(HDC dc,const char*s,R r,int x){usize n=slen(s);int local=x-(r.x+12);if(local<=0)return 0;for(usize i=1;i<=n;++i){int w=textw(dc,fMono,s,i);if(local<w){int prev=textw(dc,fMono,s,i-1);return local-prev < w-local ? i-1:i;}}return n;}
static void field(HDC dc,R r,const char*s,bool focused){box(dc,r,bSurf,focused?pAccent:pBorder,8);usize n=slen(s);if(focused){usize a=g_anchor<g_cursor?g_anchor:g_cursor,b=g_anchor<g_cursor?g_cursor:g_anchor;if(a>n)a=n;if(b>n)b=n;if(a!=b){int x1=r.x+12+textw(dc,fMono,s,a),x2=r.x+12+textw(dc,fMono,s,b);RECT_ sel{x1,r.y+7,x2,r.y+r.h-7};FillRect(dc,&sel,bSelect);}}text(dc,s,{r.x+12,r.y,r.w-24,r.h},Z50,fMono,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);if(focused&&g_cursor<=n){int cx=r.x+12+textw(dc,fMono,s,g_cursor);if(cx<r.x+r.w-8){HGDIOBJ old=SelectObject(dc,(HGDIOBJ)pAccent);MoveToEx(dc,cx,r.y+8,nullptr);LineTo(dc,cx,r.y+r.h-8);SelectObject(dc,old);}}}
static int layoutItemHeight(const LayoutItem&li){return li.type==LayoutTitle?46:(li.type==LayoutSubtitle?34:130);}static int layoutContentHeight(){int h=0;for(usize i=0;i<g_app.layoutCount;++i)h+=layoutItemHeight(g_app.layout[i]);return h;}static int entryY(usize entryIndex){int y=94;for(usize i=0;i<g_app.layoutCount;++i){LayoutItem&li=g_app.layout[i];if(li.type==LayoutField&&li.entryIndex==entryIndex)return y;y+=layoutItemHeight(li);}return 104+(int)entryIndex*130;}static R entryRow(usize i,int w){int y=entryY(i);return R{20,y,w-40,116};} static R editRect(usize i,int w){R row=entryRow(i,w);int buttons=100+112+20;int iw=row.w-28-buttons;if(iw<150)iw=150;return R{row.x+14,row.y+68,iw,38};} static R applyRect(usize i,int w){R e=editRect(i,w);return R{e.x+e.w+10,e.y,100,38};} static R freezeRect(usize i,int w){R a=applyRect(i,w);return R{a.x+a.w+10,a.y,112,38};}
static void render(HDC dc){RECT_ c{};GetClientRect(g_hwnd,&c);int w=(int)c.right,h=(int)c.bottom;RECT_ all{0,0,w,h};FillRect(dc,&all,bBg);text(dc,g_app.title,{20,14,w-40,30},Z50,fTitle,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);char st[320]{};usize n=0;if(g_proc){appends(st,sizeof(st),n,"Connected to ");appends(st,sizeof(st),n,g_app.process);appends(st,sizeof(st),n,"  |  PID ");appendu(st,sizeof(st),n,g_pid);}else{appends(st,sizeof(st),n,"Waiting for ");appends(st,sizeof(st),n,g_app.process);appends(st,sizeof(st),n,"...");}st[n]=0;text(dc,st,{20,48,w-40,22},g_proc?GREEN:AMBER,fSmall,DT_LEFT|DT_VCENTER|DT_SINGLELINE);
 int ly=94;for(usize lii=0;lii<g_app.layoutCount;++lii){LayoutItem&li=g_app.layout[lii];if(li.type==LayoutTitle){text(dc,li.text,{20,ly,w-40,32},Z50,fTitle,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);ly+=layoutItemHeight(li);continue;}if(li.type==LayoutSubtitle){text(dc,li.text,{20,ly,w-40,24},Z400,fNorm,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);ly+=layoutItemHeight(li);continue;}if(li.entryIndex>=g_app.entryCount){ly+=layoutItemHeight(li);continue;}usize i=li.entryIndex;Entry&x=g_app.entries[i];R row{20,ly,w-40,116};box(dc,row,bPanel,pBorder,11);text(dc,x.label,{row.x+14,row.y+10,row.w-28,24},Z50,fBold,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);char info[320]{};n=0;if(g_proc&&x.valid){if(x.showCurrent){u8 raw[8]{};if(readentry(x,raw)){appends(info,sizeof(info),n,"Current value: ");char v[96]{};formatv(v,sizeof(v),x.type,raw);appends(info,sizeof(info),n,v);}else appends(info,sizeof(info),n,"Current value: read failed");}else appends(info,sizeof(info),n,"Current value: hidden");appends(info,sizeof(info),n,"   |   ");appends(info,sizeof(info),n,tname(x.type));appends(info,sizeof(info),n,"   |   consensus ");appendu(info,sizeof(info),n,x.agree);appendc(info,sizeof(info),n,'/');appendu(info,sizeof(info),n,x.resolvedCount);}else appends(info,sizeof(info),n,g_proc?"Pointer unavailable":"Waiting for process");info[n]=0;text(dc,info,{row.x+14,row.y+38,row.w-28,22},x.valid?Z400:AMBER,fSmall,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);if(x.allowWrite){R er=editRect(i,w);field(dc,er,x.edit,g_focus==(int)i);button(dc,applyRect(i,w),"Apply",x.valid,true);}if(x.allowFreeze)button(dc,freezeRect(i,w),x.freeze?"Freeze: ON":"Freeze: OFF",x.valid,x.freeze);ly+=layoutItemHeight(li);}
 box(dc,{16,h-47,w-32,31},bPanel,pBorder,8);text(dc,g_status,{28,h-47,w-56,31},Z400,fSmall,DT_LEFT|DT_VCENTER|DT_SINGLELINE|DT_END_ELLIPSIS);
}
static void setstatus(const char*s){scopy(g_status,sizeof(g_status),s);InvalidateRect(g_hwnd,nullptr,0);} static void focus_entry(int idx,usize cursor){g_focus=idx;if(idx<0){g_cursor=g_anchor=0;return;}usize n=slen(g_app.entries[idx].edit);g_cursor=g_anchor=cursor>n?n:cursor;InvalidateRect(g_hwnd,nullptr,0);}
static void click(int x,int y){RECT_ c{};GetClientRect(g_hwnd,&c);int w=(int)c.right;HDC dc=CreateCompatibleDC(nullptr);for(usize i=0;i<g_app.entryCount;++i){Entry&e=g_app.entries[i];if(e.allowWrite&&inside(editRect(i,w),x,y)){usize pos=caret_from_x(dc,e.edit,editRect(i,w),x);DeleteDC(dc);focus_entry((int)i,pos);return;}if(inside(applyRect(i,w),x,y)&&e.allowWrite&&e.valid){if(dc)DeleteDC(dc);if(writeentry(e,e.edit)){setstatus("Value written successfully.");if(e.freeze&&encode(e.type,e.edit,e.freezeBytes)){} }else setstatus("Write failed. Check the value and pointer.");return;}if(inside(freezeRect(i,w),x,y)&&e.allowFreeze&&e.valid){if(dc)DeleteDC(dc);if(e.freeze){e.freeze=false;setstatus("Freeze disabled.");}else{if(encode(e.type,e.edit,e.freezeBytes)){e.freeze=true;writeentry(e,e.edit);setstatus("Freeze enabled.");}else setstatus("Invalid value for this type.");}return;}}if(dc)DeleteDC(dc);focus_entry(-1,0);}
static void dblclick(int x,int y){RECT_ c{};GetClientRect(g_hwnd,&c);int w=(int)c.right;for(usize i=0;i<g_app.entryCount;++i){if(g_app.entries[i].allowWrite&&inside(editRect(i,w),x,y)){g_focus=(int)i;g_anchor=0;g_cursor=slen(g_app.entries[i].edit);InvalidateRect(g_hwnd,nullptr,0);return;}}}
static void erase_selection(Entry&e){usize n=slen(e.edit);usize a=g_anchor<g_cursor?g_anchor:g_cursor,b=g_anchor<g_cursor?g_cursor:g_anchor;if(a>n)a=n;if(b>n)b=n;if(a==b)return;for(usize i=a;i<=n-(b-a);++i)e.edit[i]=e.edit[i+(b-a)];g_cursor=g_anchor=a;}
static void insert_char(Entry&e,char c){erase_selection(e);usize n=slen(e.edit);if(n+1>=sizeof(e.edit))return;if(g_cursor>n)g_cursor=n;for(usize i=n+1;i>g_cursor;--i)e.edit[i]=e.edit[i-1];e.edit[g_cursor++]=c;g_anchor=g_cursor;}
static void char_input(char c){if(g_focus<0||g_focus>=(int)g_app.entryCount)return;Entry&e=g_app.entries[g_focus];if(c==8){if(g_anchor!=g_cursor)erase_selection(e);else if(g_cursor){usize n=slen(e.edit);for(usize i=g_cursor-1;i<n;++i)e.edit[i]=e.edit[i+1];--g_cursor;g_anchor=g_cursor;}}else if(c==13){RECT_ r{};GetClientRect(g_hwnd,&r);R a=applyRect((usize)g_focus,(int)r.right);click(a.x+2,a.y+2);return;}else if((c>='0'&&c<='9')||c=='-'||c=='+'||c=='.'||c=='e'||c=='E')insert_char(e,c);InvalidateRect(g_hwnd,nullptr,0);}
static void keydown(UINT k){if(g_focus<0||g_focus>=(int)g_app.entryCount)return;Entry&e=g_app.entries[g_focus];bool ctrl=(GetKeyState(0x11)&0x8000)!=0,shift=(GetKeyState(0x10)&0x8000)!=0;usize n=slen(e.edit);if(ctrl&&(k=='A'||k=='a')){g_anchor=0;g_cursor=n;InvalidateRect(g_hwnd,nullptr,0);return;}if(k==0x2E){if(g_anchor!=g_cursor)erase_selection(e);else if(g_cursor<n)for(usize i=g_cursor;i<n;++i)e.edit[i]=e.edit[i+1];}else if(k==0x25||k==0x27||k==0x24||k==0x23){usize next=g_cursor;if(k==0x25&&next)next--;else if(k==0x27&&next<n)next++;else if(k==0x24)next=0;else if(k==0x23)next=n;if(!shift)g_anchor=next;g_cursor=next;}InvalidateRect(g_hwnd,nullptr,0);}
static void resources(){Z950=g_app.bg;Z900=g_app.panel;Z800=g_app.surface;Z400=g_app.muted;Z50=g_app.text;BLUE=g_app.accent;Z700=mixc(g_app.surface,g_app.muted,70);bBg=CreateSolidBrush(Z950);bPanel=CreateSolidBrush(Z900);bSurf=CreateSolidBrush(Z800);bHover=CreateSolidBrush(Z700);bAccent=CreateSolidBrush(BLUE);bGood=CreateSolidBrush(rgb(16,185,129));bWarn=CreateSolidBrush(rgb(245,158,11));bSelect=CreateSolidBrush(mixc(BLUE,Z900,70));pBorder=CreatePen(PS_SOLID,1,mixc(Z800,Z400,70));pAccent=CreatePen(PS_SOLID,1,BLUE);fNorm=CreateFontA(-16,0,0,0,FW_NORMAL,0,0,0,1,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");fSmall=CreateFontA(-14,0,0,0,FW_NORMAL,0,0,0,1,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");fBold=CreateFontA(-16,0,0,0,FW_SEMIBOLD,0,0,0,1,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");fTitle=CreateFontA(-24,0,0,0,FW_SEMIBOLD,0,0,0,1,0,0,CLEARTYPE_QUALITY,0,"Segoe UI");fMono=CreateFontA(-15,0,0,0,FW_NORMAL,0,0,0,1,0,0,CLEARTYPE_QUALITY,0,"Consolas");}
static void cleanup(){g_stop=1;detach();for(usize i=0;i<g_app.entryCount;++i){Entry&e=g_app.entries[i];if(e.chains){for(usize j=0;j<e.chainCount;++j)if(e.chains[j].offsets)HeapFree(g_heap,0,e.chains[j].offsets);HeapFree(g_heap,0,e.chains);}}HGDIOBJ o[]={bBg,bPanel,bSurf,bHover,bAccent,bGood,bWarn,bSelect,pBorder,pAccent,fNorm,fSmall,fBold,fTitle,fMono};for(unsigned i=0;i<sizeof(o)/sizeof(o[0]);++i)if(o[i])DeleteObject(o[i]);}
static LRESULT __stdcall wnd(HWND h,UINT m,WPARAM wp,LPARAM lp){if(m==WM_CREATE){g_hwnd=h;resources();SetTimer(h,1,750,nullptr);return 0;}if(m==WM_TIMER){if(!g_proc){find_process();}else{HANDLE test=OpenProcess(PROCESS_QUERY_INFORMATION,0,g_pid);if(!test)detach();else CloseHandle(test);if(g_proc){refresh_modules();for(usize i=0;i<g_app.entryCount;++i)resolve_entry(g_app.entries[i]);}}InvalidateRect(h,nullptr,0);return 0;}if(m==WM_MOUSEMOVE){mouseX=(short)(lp&0xFFFF);mouseY=(short)((lp>>16)&0xFFFF);InvalidateRect(h,nullptr,0);return 0;}if(m==WM_LBUTTONDOWN){click((short)(lp&0xFFFF),(short)((lp>>16)&0xFFFF));return 0;}if(m==WM_LBUTTONDBLCLK){dblclick((short)(lp&0xFFFF),(short)((lp>>16)&0xFFFF));return 0;}if(m==WM_KEYDOWN){keydown((UINT)wp);return 0;}if(m==WM_CHAR){char_input((char)(wp&0xFF));return 0;}if(m==WM_PAINT){PAINTSTRUCT_ ps{};HDC dc=BeginPaint(h,&ps);RECT_ c{};GetClientRect(h,&c);HDC mem=CreateCompatibleDC(dc);HBITMAP bm=CreateCompatibleBitmap(dc,(int)c.right,(int)c.bottom);HGDIOBJ old=SelectObject(mem,(HGDIOBJ)bm);render(mem);BitBlt(dc,0,0,(int)c.right,(int)c.bottom,mem,0,0,SRCCOPY);SelectObject(mem,old);DeleteObject((HGDIOBJ)bm);DeleteDC(mem);EndPaint(h,&ps);return 0;}if(m==WM_CLOSE){g_stop=1;return DefWindowProcA(h,m,wp,lp);}if(m==WM_DESTROY){KillTimer(h,1);cleanup();PostQuitMessage(0);return 0;}return DefWindowProcA(h,m,wp,lp);}

extern "C" void trainerCRTStartup(){SetProcessDPIAware();g_heap=GetProcessHeap();if(!load_package()){MessageBoxA(nullptr,"This trainer does not contain a valid Cheat Wizard package. Build it with cw-trainer-builder.exe.","Cheat Wizard Trainer",MB_OK|MB_ICONERROR);ExitProcess(2);}DWORD tid=0;HANDLE th=CreateThread(nullptr,0,freeze_thread,nullptr,0,&tid);if(th)CloseHandle(th);HINSTANCE inst=GetModuleHandleA(nullptr);WNDCLASSEXA_ wc{};wc.cbSize=sizeof(wc);wc.style=CS_DBLCLKS;wc.lpfnWndProc=wnd;wc.hInstance=inst;wc.hCursor=LoadCursorA(nullptr,(const char*)(uptr)32512);wc.hIcon=LoadIconA(inst,(const char*)(uptr)1);wc.hIconSm=wc.hIcon;wc.lpszClassName="CheatWizardTrainerRuntime";if(!RegisterClassExA(&wc))ExitProcess(3);int height=94+layoutContentHeight()+70;if((int)g_app.height>height)height=(int)g_app.height;if(height<360)height=360;if(height>980)height=980;int width=(int)g_app.width;if(width<620)width=620;HWND h=CreateWindowExA(0,"CheatWizardTrainerRuntime",g_app.title,WS_CAPTION|WS_SYSMENU|WS_MINIMIZEBOX|WS_THICKFRAME,100,80,width,height,nullptr,nullptr,inst,nullptr);if(!h)ExitProcess(4);g_hwnd=h;ShowWindow(h,SW_SHOW);UpdateWindow(h);MSG_ msg{};while(GetMessageA(&msg,nullptr,0,0)>0){TranslateMessage(&msg);DispatchMessageA(&msg);}ExitProcess(0);}
