// Cheat Wizard Trainer Builder - no CRT/STL Windows x64 console tool.
// Usage: cw-trainer-builder.exe build trainer.cwtrainer -o MyTrainer.exe
// Reads the JSON project, validates .cwptr / legacy .mcptr files, and appends a normalized
// package to the embedded trainer runtime template, producing one standalone EXE.

using u8=unsigned char;using u16=unsigned short;using u32=unsigned int;using u64=unsigned long long;using i32=int;using i64=long long;using usize=unsigned long long;using HANDLE=void*;using LPVOID=void*;using LPCVOID=const void*;using BOOL=int;using DWORD=unsigned long;using WORD=unsigned short;using SIZE_T=unsigned long long;
#ifndef __stdcall
#define __stdcall
#endif
struct LARGE_INTEGER_{i64 QuadPart;};
extern "C"{
__declspec(dllimport) HANDLE __stdcall GetStdHandle(DWORD);__declspec(dllimport) BOOL __stdcall WriteFile(HANDLE,LPCVOID,DWORD,DWORD*,LPVOID);__declspec(dllimport) HANDLE __stdcall CreateFileA(const char*,DWORD,DWORD,LPVOID,DWORD,DWORD,HANDLE);__declspec(dllimport) BOOL __stdcall ReadFile(HANDLE,LPVOID,DWORD,DWORD*,LPVOID);__declspec(dllimport) BOOL __stdcall CloseHandle(HANDLE);__declspec(dllimport) BOOL __stdcall GetFileSizeEx(HANDLE,LARGE_INTEGER_*);__declspec(dllimport) void __stdcall ExitProcess(u32);__declspec(dllimport) HANDLE __stdcall GetProcessHeap();__declspec(dllimport) LPVOID __stdcall HeapAlloc(HANDLE,DWORD,SIZE_T);__declspec(dllimport) BOOL __stdcall HeapFree(HANDLE,DWORD,LPVOID);__declspec(dllimport) char* __stdcall GetCommandLineA();__declspec(dllimport) BOOL __stdcall SetFilePointerEx(HANDLE,LARGE_INTEGER_,LARGE_INTEGER_*,DWORD);__declspec(dllimport) HANDLE __stdcall BeginUpdateResourceA(const char*,BOOL);__declspec(dllimport) BOOL __stdcall UpdateResourceA(HANDLE,const char*,const char*,WORD,LPVOID,DWORD);__declspec(dllimport) BOOL __stdcall EndUpdateResourceA(HANDLE,BOOL);
}
#if defined(CW_USE_STANDARD_CRT)
#include <cstring>
using std::memcpy;
using std::memset;
#else
// Volatile accesses prevent optimized MSVC builds from folding these no-CRT
// functions into recursive calls to memcpy/memset.
extern "C" void* memcpy(void*d,const void*s,usize n){auto*a=(volatile u8*)d;auto*b=(const volatile u8*)s;for(usize i=0;i<n;++i)a[i]=b[i];return d;}extern "C" void* memset(void*d,int c,usize n){auto*a=(volatile u8*)d;for(usize i=0;i<n;++i)a[i]=(u8)c;return d;}
#endif
#include "TrainerRuntimeBlob.hpp"
static constexpr DWORD STD_OUTPUT_HANDLE=(DWORD)-11,GENERIC_READ=0x80000000UL,GENERIC_WRITE=0x40000000UL,CREATE_ALWAYS=2,OPEN_EXISTING=3,FILE_ATTRIBUTE_NORMAL=0x80,FILE_BEGIN=0;static constexpr usize MAX_ENTRIES=8,MAX_LAYOUT=32,MAX_FILE=16ULL*1024*1024;
static HANDLE g_out=nullptr,g_heap=nullptr;
static usize slen(const char*s){usize n=0;if(s)while(s[n])++n;return n;}static bool seq(const char*a,const char*b){if(!a||!b)return false;while(*a&&*b){if(*a++!=*b++)return false;}return *a==*b;}static char low(char c){return c>='A'&&c<='Z'?(char)(c+32):c;}static bool sieq(const char*a,const char*b){if(!a||!b)return false;while(*a&&*b){if(low(*a++)!=low(*b++))return false;}return *a==*b;}static void scopy(char*d,usize cap,const char*s){if(!cap)return;usize i=0;if(s)for(;i+1<cap&&s[i];++i)d[i]=s[i];d[i]=0;}static void puts_(const char*s){DWORD w=0;if(g_out&&s)WriteFile(g_out,s,(DWORD)slen(s),&w,nullptr);}static void line(const char*s){puts_(s);puts_("\r\n");}
static void appendc(char*b,usize cap,usize&n,char c){if(n+1<cap)b[n++]=c;}static void appends(char*b,usize cap,usize&n,const char*s){while(s&&*s&&n+1<cap)b[n++]=*s++;}static void appendu(char*b,usize cap,usize&n,u64 v){char t[32];int k=0;if(!v)t[k++]='0';while(v&&k<31){t[k++]=(char)('0'+v%10);v/=10;}while(k--)appendc(b,cap,n,t[k]);}
static bool readall(const char*path,u8*&data,usize&size){data=nullptr;size=0;HANDLE f=CreateFileA(path,GENERIC_READ,1|2,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if((u64)f==~0ULL)return false;LARGE_INTEGER_ z{};if(!GetFileSizeEx(f,&z)||z.QuadPart<0||(u64)z.QuadPart>MAX_FILE){CloseHandle(f);return false;}size=(usize)z.QuadPart;data=(u8*)HeapAlloc(g_heap,0,size+1);if(!data){CloseHandle(f);return false;}DWORD got=0;bool ok=ReadFile(f,data,(DWORD)size,&got,nullptr)&&got==(DWORD)size;CloseHandle(f);if(!ok){HeapFree(g_heap,0,data);data=nullptr;size=0;return false;}data[size]=0;return true;}
static bool writeall(const char*path,const u8*data,usize size){HANDLE f=CreateFileA(path,GENERIC_WRITE,0,nullptr,CREATE_ALWAYS,FILE_ATTRIBUTE_NORMAL,nullptr);if((u64)f==~0ULL)return false;usize off=0;bool ok=true;while(off<size){DWORD chunk=(DWORD)((size-off)>0x40000000ULL?0x40000000ULL:(size-off)),w=0;if(!WriteFile(f,data+off,chunk,&w,nullptr)||w!=chunk){ok=false;break;}off+=w;}CloseHandle(f);return ok;}
static bool appendfile(const char*path,const u8*data,usize size,u64&start){HANDLE f=CreateFileA(path,GENERIC_READ|GENERIC_WRITE,1|2,nullptr,OPEN_EXISTING,FILE_ATTRIBUTE_NORMAL,nullptr);if((u64)f==~0ULL)return false;LARGE_INTEGER_ z{};if(!GetFileSizeEx(f,&z)){CloseHandle(f);return false;}start=(u64)z.QuadPart;LARGE_INTEGER_ p{z.QuadPart};if(!SetFilePointerEx(f,p,nullptr,FILE_BEGIN)){CloseHandle(f);return false;}usize off=0;bool ok=true;while(off<size){DWORD chunk=(DWORD)((size-off)>0x40000000ULL?0x40000000ULL:(size-off)),w=0;if(!WriteFile(f,data+off,chunk,&w,nullptr)||w!=chunk){ok=false;break;}off+=w;}CloseHandle(f);return ok;}
static int hd(char c){if(c>='0'&&c<='9')return c-'0';if(c>='a'&&c<='f')return c-'a'+10;if(c>='A'&&c<='F')return c-'A'+10;return-1;}static bool colorhex(const char*s,u32&out){if(!s||s[0]!='#'||slen(s)!=7)return false;int v[6];for(int i=0;i<6;++i){v[i]=hd(s[i+1]);if(v[i]<0)return false;}u8 r=(u8)((v[0]<<4)|v[1]),g=(u8)((v[2]<<4)|v[3]),b=(u8)((v[4]<<4)|v[5]);out=(u32)r|((u32)g<<8)|((u32)b<<16);return true;}
static bool applyicon(const char*exe,const char*ico){if(!ico||!*ico)return true;u8*d=nullptr;usize z=0;if(!readall(ico,d,z)){line("Could not read visual.icon .ico file.");return false;}if(z<6||((u16)d[0]|((u16)d[1]<<8))!=0||((u16)d[2]|((u16)d[3]<<8))!=1){HeapFree(g_heap,0,d);line("Invalid .ico file.");return false;}u16 count=(u16)d[4]|((u16)d[5]<<8);if(!count||count>64||z<6+(usize)count*16){HeapFree(g_heap,0,d);line("Invalid .ico directory.");return false;}HANDLE u=BeginUpdateResourceA(exe,0);if(!u){HeapFree(g_heap,0,d);line("Could not open generated EXE resources for icon update.");return false;}bool ok=true;usize gz=6+(usize)count*14;u8*g=(u8*)HeapAlloc(g_heap,0,gz);if(!g){EndUpdateResourceA(u,1);HeapFree(g_heap,0,d);return false;}g[0]=0;g[1]=0;g[2]=1;g[3]=0;g[4]=(u8)count;g[5]=(u8)(count>>8);u8*gp=g+6;for(u16 i=0;i<count&&ok;++i){const u8*e=d+6+(usize)i*16;u32 bytes=(u32)e[8]|((u32)e[9]<<8)|((u32)e[10]<<16)|((u32)e[11]<<24),off=(u32)e[12]|((u32)e[13]<<8)|((u32)e[14]<<16)|((u32)e[15]<<24);if(!bytes||(u64)off+bytes>z){ok=false;break;}WORD id=(WORD)(i+1);if(!UpdateResourceA(u,(const char*)(u64)3,(const char*)(u64)id,0,d+off,bytes)){ok=false;break;}for(int k=0;k<12;++k)*gp++=e[k];*gp++=(u8)id;*gp++=(u8)(id>>8);}if(ok)ok=UpdateResourceA(u,(const char*)(u64)14,(const char*)(u64)1,0,g,(DWORD)gz)!=0;HeapFree(g_heap,0,g);BOOL ended=EndUpdateResourceA(u,ok?0:1);HeapFree(g_heap,0,d);if(!ok||!ended){line("Could not apply application icon to output EXE.");return false;}return true;}

static bool isabs(const char*p){if(!p)return false;return ((((p[0]>='A'&&p[0]<='Z')||(p[0]>='a'&&p[0]<='z'))&&p[1]==':'&&(p[2]=='\\'||p[2]=='/'))||(p[0]=='\\'&&p[1]=='\\'));}static void dirname(const char*p,char*out,usize cap){usize n=slen(p),last=0;for(usize i=0;i<n;++i)if(p[i]=='\\'||p[i]=='/')last=i+1;if(!last){scopy(out,cap,"");return;}if(last>=cap)last=cap-1;for(usize i=0;i<last;++i)out[i]=p[i];out[last]=0;}static bool joinpath(const char*base,const char*rel,char*out,usize cap){if(isabs(rel)){scopy(out,cap,rel);return slen(rel)<cap;}usize n=0;for(;base&&*base&&n+1<cap;)out[n++]=*base++;for(;rel&&*rel&&n+1<cap;)out[n++]=*rel++;out[n]=0;return rel&&!*rel;}

struct J{const char*p;const char*e;};static void ws(J&j){while(j.p<j.e&&(*j.p==' '||*j.p=='\t'||*j.p=='\r'||*j.p=='\n'))++j.p;}static bool ch(J&j,char c){ws(j);if(j.p>=j.e||*j.p!=c)return false;++j.p;return true;}static bool jstr(J&j,char*out,usize cap){ws(j);if(j.p>=j.e||*j.p!='"')return false;++j.p;usize n=0;while(j.p<j.e){char c=*j.p++;if(c=='"'){if(cap)out[n<cap?n:cap-1]=0;return true;}if(c=='\\'){if(j.p>=j.e)return false;char x=*j.p++;if(x=='"'||x=='\\'||x=='/')c=x;else if(x=='n')c='\n';else if(x=='r')c='\r';else if(x=='t')c='\t';else return false;}if(n+1<cap)out[n++]=c;}return false;}static bool jbool(J&j,bool&v){ws(j);if(j.e-j.p>=4&&j.p[0]=='t'&&j.p[1]=='r'&&j.p[2]=='u'&&j.p[3]=='e'){j.p+=4;v=true;return true;}if(j.e-j.p>=5&&j.p[0]=='f'&&j.p[1]=='a'&&j.p[2]=='l'&&j.p[3]=='s'&&j.p[4]=='e'){j.p+=5;v=false;return true;}return false;}static bool jnum(J&j,u32&v){ws(j);if(j.p>=j.e||*j.p<'0'||*j.p>'9')return false;u64 x=0;while(j.p<j.e&&*j.p>='0'&&*j.p<='9'){x=x*10+(u64)(*j.p-'0');if(x>0xFFFFFFFFULL)return false;++j.p;}v=(u32)x;return true;}
static bool skipv(J&j);static bool skipobj(J&j){if(!ch(j,'{'))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}for(;;){char k[64];if(!jstr(j,k,sizeof(k))||!ch(j,':')||!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}if(!ch(j,','))return false;}}static bool skiparr(J&j){if(!ch(j,'['))return false;ws(j);if(j.p<j.e&&*j.p==']'){++j.p;return true;}for(;;){if(!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p==']'){++j.p;return true;}if(!ch(j,','))return false;}}static bool skipv(J&j){ws(j);if(j.p>=j.e)return false;if(*j.p=='"'){char t[2];return jstr(j,t,sizeof(t));}if(*j.p=='{')return skipobj(j);if(*j.p=='[')return skiparr(j);bool b=false;if(jbool(j,b))return true;u32 n=0;if(jnum(j,n))return true;if(j.e-j.p>=4&&j.p[0]=='n'&&j.p[1]=='u'&&j.p[2]=='l'&&j.p[3]=='l'){j.p+=4;return true;}return false;}
enum LayoutType:u8{LayoutTitle=0,LayoutSubtitle=1,LayoutField=2};struct E{char id[64],label[128],profile[1024],def[64];bool show=true,write=true,freeze=true;u8*bytes=nullptr;usize size=0;};struct L{u8 type;char text[192],entry[64];u32 entryIndex;};struct Project{char title[128],process[260],icon[1024],bg[16],panel[16],surface[16],accent[16],text[16],muted[16];u32 width,height;E entries[MAX_ENTRIES];usize count;L layout[MAX_LAYOUT];usize layoutCount;};
static bool parse_trainer_obj(J&j,Project&p){if(!ch(j,'{'))return false;for(;;){ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}char k[64];if(!jstr(j,k,sizeof(k))||!ch(j,':'))return false;if(seq(k,"name")){if(!jstr(j,p.title,sizeof(p.title)))return false;}else if(seq(k,"process")){if(!jstr(j,p.process,sizeof(p.process)))return false;}else if(!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}if(!ch(j,','))return false;}}
static bool parse_window_obj(J&j,Project&p){if(!ch(j,'{'))return false;for(;;){ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}char k[64];if(!jstr(j,k,sizeof(k))||!ch(j,':'))return false;if(seq(k,"width")){if(!jnum(j,p.width))return false;}else if(seq(k,"height")){if(!jnum(j,p.height))return false;}else if(!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}if(!ch(j,','))return false;}}
static bool parse_visual_obj(J&j,Project&p){if(!ch(j,'{'))return false;for(;;){ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}char k[64];if(!jstr(j,k,sizeof(k))||!ch(j,':'))return false;if(seq(k,"icon")){if(!jstr(j,p.icon,sizeof(p.icon)))return false;}else if(seq(k,"background")){if(!jstr(j,p.bg,sizeof(p.bg)))return false;}else if(seq(k,"panel")){if(!jstr(j,p.panel,sizeof(p.panel)))return false;}else if(seq(k,"surface")){if(!jstr(j,p.surface,sizeof(p.surface)))return false;}else if(seq(k,"accent")){if(!jstr(j,p.accent,sizeof(p.accent)))return false;}else if(seq(k,"text")){if(!jstr(j,p.text,sizeof(p.text)))return false;}else if(seq(k,"muted")){if(!jstr(j,p.muted,sizeof(p.muted)))return false;}else if(!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}if(!ch(j,','))return false;}}
static bool parse_entry(J&j,E&e){if(!ch(j,'{'))return false;for(;;){ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}char k[64];if(!jstr(j,k,sizeof(k))||!ch(j,':'))return false;if(seq(k,"id")){if(!jstr(j,e.id,sizeof(e.id)))return false;}else if(seq(k,"label")){if(!jstr(j,e.label,sizeof(e.label)))return false;}else if(seq(k,"profile")){if(!jstr(j,e.profile,sizeof(e.profile)))return false;}else if(seq(k,"defaultValue")||seq(k,"default")){if(!jstr(j,e.def,sizeof(e.def)))return false;}else if(seq(k,"showCurrent")){if(!jbool(j,e.show))return false;}else if(seq(k,"allowWrite")){if(!jbool(j,e.write))return false;}else if(seq(k,"allowFreeze")){if(!jbool(j,e.freeze))return false;}else if(!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;return true;}if(!ch(j,','))return false;}}
static bool parse_entries(J&j,Project&p){if(!ch(j,'['))return false;ws(j);if(j.p<j.e&&*j.p==']'){++j.p;return true;}for(;;){if(p.count>=MAX_ENTRIES)return false;E& e=p.entries[p.count];e.show=true;e.write=true;e.freeze=true;if(!parse_entry(j,e))return false;++p.count;ws(j);if(j.p<j.e&&*j.p==']'){++j.p;return true;}if(!ch(j,','))return false;}}
static bool parse_layout_item(J&j,L&l){if(!ch(j,'{'))return false;char type[24]{};for(;;){ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;break;}char k[64];if(!jstr(j,k,sizeof(k))||!ch(j,':'))return false;if(seq(k,"type")){if(!jstr(j,type,sizeof(type)))return false;}else if(seq(k,"text")){if(!jstr(j,l.text,sizeof(l.text)))return false;}else if(seq(k,"entry")){if(!jstr(j,l.entry,sizeof(l.entry)))return false;}else if(!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;break;}if(!ch(j,','))return false;}if(seq(type,"title")){l.type=LayoutTitle;return l.text[0]!=0&&!l.entry[0];}if(seq(type,"subtitle")){l.type=LayoutSubtitle;return l.text[0]!=0&&!l.entry[0];}if(seq(type,"field")){l.type=LayoutField;return l.entry[0]!=0&&!l.text[0];}return false;}
static bool parse_layout(J&j,Project&p){if(!ch(j,'['))return false;ws(j);if(j.p<j.e&&*j.p==']'){++j.p;return true;}for(;;){if(p.layoutCount>=MAX_LAYOUT)return false;L&l=p.layout[p.layoutCount];memset(&l,0,sizeof(l));if(!parse_layout_item(j,l))return false;++p.layoutCount;ws(j);if(j.p<j.e&&*j.p==']'){++j.p;return true;}if(!ch(j,','))return false;}}
static bool normalize_layout(Project&p){if(!p.layoutCount){if(p.count>MAX_LAYOUT)return false;for(usize i=0;i<p.count;++i){L&l=p.layout[p.layoutCount++];l.type=LayoutField;l.entryIndex=(u32)i;scopy(l.entry,sizeof(l.entry),p.entries[i].id);}return true;}bool used[MAX_ENTRIES]{};for(usize i=0;i<p.layoutCount;++i){L&l=p.layout[i];if(l.type!=LayoutField){l.entryIndex=0xFFFFFFFFu;continue;}int found=-1;for(usize k=0;k<p.count;++k)if(seq(l.entry,p.entries[k].id)){found=(int)k;break;}if(found<0||used[found])return false;used[found]=true;l.entryIndex=(u32)found;}for(usize i=0;i<p.count;++i)if(!used[i])return false;return true;}
static bool parse_project(const u8*data,usize size,Project&p){J j{(const char*)data,(const char*)data+size};if(!ch(j,'{'))return false;char format[64]{};u32 version=0;for(;;){ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;break;}char k[64];if(!jstr(j,k,sizeof(k))||!ch(j,':'))return false;if(seq(k,"format")){if(!jstr(j,format,sizeof(format)))return false;}else if(seq(k,"version")){if(!jnum(j,version))return false;}else if(seq(k,"trainer")){if(!parse_trainer_obj(j,p))return false;}else if(seq(k,"window")){if(!parse_window_obj(j,p))return false;}else if(seq(k,"visual")){if(!parse_visual_obj(j,p))return false;}else if(seq(k,"entries")){if(!parse_entries(j,p))return false;}else if(seq(k,"layout")){if(!parse_layout(j,p))return false;}else if(!skipv(j))return false;ws(j);if(j.p<j.e&&*j.p=='}'){++j.p;break;}if(!ch(j,','))return false;}ws(j);return j.p==j.e&&(seq(format,"cheat-wizard-trainer")||seq(format,"minice-trainer"))&&version==1&&p.title[0]&&p.process[0]&&p.count>0&&normalize_layout(p);}
static u16 r16at(const u8*p){return (u16)p[0]|((u16)p[1]<<8);}static u32 r32at(const u8*p){return (u32)p[0]|((u32)p[1]<<8)|((u32)p[2]<<16)|((u32)p[3]<<24);}static u64 r64at(const u8*p){u64 v=0;for(int i=0;i<8;++i)v|=(u64)p[i]<<(i*8);return v;}
static bool profile_meta(const u8*d,usize z,char*proc,usize cap){
 const char m[8]={'C','W','P','R','O','F','0','1'},legacy[8]={'M','C','E','P','R','O','F','1'};if(z<30)return false;bool magicOk=true,legacyOk=true;for(int i=0;i<8;++i){if(d[i]!=(u8)m[i])magicOk=false;if(d[i]!=(u8)legacy[i])legacyOk=false;}if(!magicOk&&!legacyOk)return false;
 u32 ver=r32at(d+8),ps=r32at(d+12),tc=r32at(d+16);u16 pl=r16at(d+20);u64 cc=r64at(d+22);
 if(ver!=1||(ps!=4&&ps!=8)||tc>5||!cc||cc>100000||30ULL+pl>z||pl>=cap)return false;
 const u8*p=d+30,*e=d+z;for(u16 i=0;i<pl;++i)proc[i]=(char)p[i];proc[pl]=0;p+=pl;
 for(u64 i=0;i<cc;++i){if((usize)(e-p)<2)return false;u16 ml=r16at(p);p+=2;if(!ml||ml>4096||(usize)(e-p)<(usize)ml+12)return false;p+=ml;p+=8;u32 depth=r32at(p);p+=4;if(!depth||depth>64||(usize)(e-p)<(usize)depth*8)return false;p+=(usize)depth*8;}
 return p==e;
}
static void w32(u8*&p,u32 v){for(int i=0;i<4;++i)*p++=(u8)(v>>(i*8));}static void w64(u8*&p,u64 v){for(int i=0;i<8;++i)*p++=(u8)(v>>(i*8));}static u32 crc32(const u8*p,usize n){u32 c=0xFFFFFFFFu;for(usize i=0;i<n;++i){c^=p[i];for(int j=0;j<8;++j)c=(c>>1)^(0xEDB88320u&((u32)-(i32)(c&1)));}return ~c;}
static bool load_profiles(Project&p,const char*manifest){char dir[1024]{};dirname(manifest,dir,sizeof(dir));for(usize i=0;i<p.count;++i){E&e=p.entries[i];if(!e.id[0]||!e.label[0]||!e.profile[0])return false;char full[1200]{};if(!joinpath(dir,e.profile,full,sizeof(full))||!readall(full,e.bytes,e.size)){char b[1500];usize n=0;appends(b,sizeof(b),n,"Could not read profile: ");appends(b,sizeof(b),n,full);b[n]=0;line(b);return false;}char pp[260]{};if(!profile_meta(e.bytes,e.size,pp,sizeof(pp))){line("Invalid pointer profile (.cwptr or legacy .mcptr).");return false;}if(pp[0]&&!sieq(pp,p.process)){char b[600];usize n=0;appends(b,sizeof(b),n,"Profile target mismatch: ");appends(b,sizeof(b),n,pp);appends(b,sizeof(b),n," != ");appends(b,sizeof(b),n,p.process);b[n]=0;line(b);return false;}}return true;}
static bool build(const char*manifest,const char*outPath){
 u8*jdata=nullptr;usize jsz=0;if(!readall(manifest,jdata,jsz)){line("Could not read trainer project (.cwtrainer or legacy JSON).");return false;}Project* pp=(Project*)HeapAlloc(g_heap,0,sizeof(Project));if(!pp){HeapFree(g_heap,0,jdata);return false;}memset(pp,0,sizeof(Project));Project& p=*pp;p.width=620;p.height=460;scopy(p.bg,sizeof(p.bg),"#09090B");scopy(p.panel,sizeof(p.panel),"#18181B");scopy(p.surface,sizeof(p.surface),"#27272A");scopy(p.accent,sizeof(p.accent),"#2563EB");scopy(p.text,sizeof(p.text),"#FAFAFA");scopy(p.muted,sizeof(p.muted),"#A1A1AA");
 bool ok=parse_project(jdata,jsz,p);HeapFree(g_heap,0,jdata);if(!ok){line("Invalid trainer JSON. See docs/TRAINER_SCHEMA.md");HeapFree(g_heap,0,pp);return false;}if(!load_profiles(p,manifest)){HeapFree(g_heap,0,pp);return false;}
 u32 cols[6]{};const char* cs[6]={p.bg,p.panel,p.surface,p.accent,p.text,p.muted};for(int i=0;i<6;++i)if(!colorhex(cs[i],cols[i])){line("Invalid visual color. Use #RRGGBB.");for(usize k=0;k<p.count;++k)if(p.entries[k].bytes)HeapFree(g_heap,0,p.entries[k].bytes);HeapFree(g_heap,0,pp);return false;}
 usize pkg=8+13*4+slen(p.title)+slen(p.process);for(usize i=0;i<p.count;++i){E&e=p.entries[i];pkg+=4*4+8+slen(e.id)+slen(e.label)+slen(e.def)+e.size;}for(usize i=0;i<p.layoutCount;++i)pkg+=12+slen(p.layout[i].text);if(pkg>64ULL*1024*1024){line("Trainer package too large.");HeapFree(g_heap,0,pp);return false;}u8*pb=(u8*)HeapAlloc(g_heap,0,pkg);if(!pb){HeapFree(g_heap,0,pp);return false;}u8*q=pb;const char pm[8]={'C','W','T','R','P','K','G','1'};memcpy(q,pm,8);q+=8;w32(q,3);w32(q,(u32)p.count);w32(q,(u32)slen(p.title));w32(q,(u32)slen(p.process));w32(q,p.width);w32(q,p.height);for(int i=0;i<6;++i)w32(q,cols[i]);w32(q,(u32)p.layoutCount);memcpy(q,p.title,slen(p.title));q+=slen(p.title);memcpy(q,p.process,slen(p.process));q+=slen(p.process);for(usize i=0;i<p.count;++i){E&e=p.entries[i];u32 fl=(e.show?1u:0u)|(e.write?2u:0u)|(e.freeze?4u:0u);w32(q,(u32)slen(e.id));w32(q,(u32)slen(e.label));w32(q,(u32)slen(e.def));w32(q,fl);w64(q,(u64)e.size);memcpy(q,e.id,slen(e.id));q+=slen(e.id);memcpy(q,e.label,slen(e.label));q+=slen(e.label);memcpy(q,e.def,slen(e.def));q+=slen(e.def);memcpy(q,e.bytes,e.size);q+=e.size;}for(usize i=0;i<p.layoutCount;++i){L&l=p.layout[i];w32(q,(u32)l.type);w32(q,l.entryIndex);w32(q,(u32)slen(l.text));memcpy(q,l.text,slen(l.text));q+=slen(l.text);}if((usize)(q-pb)!=pkg){line("Internal package size mismatch.");HeapFree(g_heap,0,pb);HeapFree(g_heap,0,pp);return false;}
 if(!writeall(outPath,g_trainer_runtime_bytes,g_trainer_runtime_size)){line("Could not write runtime template.");HeapFree(g_heap,0,pb);HeapFree(g_heap,0,pp);return false;}
 if(p.icon[0]){char dir[1024]{},full[1400]{};dirname(manifest,dir,sizeof(dir));if(!joinpath(dir,p.icon,full,sizeof(full))||!applyicon(outPath,full)){HeapFree(g_heap,0,pb);for(usize i=0;i<p.count;++i)if(p.entries[i].bytes)HeapFree(g_heap,0,p.entries[i].bytes);HeapFree(g_heap,0,pp);return false;}}
 struct Footer{char magic[8];u32 version,reserved;u64 off,size;u32 crc,reserved2;}ft{};const char fm[8]={'C','W','T','R','F','T','R','1'};memcpy(ft.magic,fm,8);ft.version=3;ft.size=(u64)pkg;ft.crc=crc32(pb,pkg);u64 off=0;if(!appendfile(outPath,pb,pkg,off)){line("Could not append trainer package.");ok=false;}ft.off=off;if(ok){u64 footerOff=0;ok=appendfile(outPath,(const u8*)&ft,sizeof(ft),footerOff);if(!ok)line("Could not append trainer footer.");}
 usize builtCount=p.count;u64 total=off+(u64)pkg+(u64)sizeof(ft);HeapFree(g_heap,0,pb);for(usize i=0;i<p.count;++i)if(p.entries[i].bytes)HeapFree(g_heap,0,p.entries[i].bytes);HeapFree(g_heap,0,pp);if(!ok)return false;char msg[1200];usize n=0;appends(msg,sizeof(msg),n,"Built: ");appends(msg,sizeof(msg),n,outPath);appends(msg,sizeof(msg),n," | entries: ");appendu(msg,sizeof(msg),n,builtCount);appends(msg,sizeof(msg),n," | single EXE bytes: ");appendu(msg,sizeof(msg),n,total);msg[n]=0;line(msg);return true;
}

static int args(char*cmd,char*av[],int max){int n=0;char*p=cmd;while(*p&&n<max){while(*p==' '||*p=='\t')++p;if(!*p)break;bool quote=false;if(*p=='"'){quote=true;++p;}av[n++]=p;char*w=p;while(*p){if(quote){if(*p=='"'){++p;break;}}else if(*p==' '||*p=='\t')break;*w++=*p++;}char*next=p;if(!quote&&(*next==' '||*next=='\t'))++next;*w=0;p=next;while(*p==' '||*p=='\t')++p;}return n;}
extern "C" void builderCRTStartup(){g_heap=GetProcessHeap();g_out=GetStdHandle(STD_OUTPUT_HANDLE);const char*raw=GetCommandLineA();usize cmdLen=slen(raw);char*cmd=(char*)HeapAlloc(g_heap,0,cmdLen+1);if(!cmd){line("Out of memory.");ExitProcess(2);}memcpy(cmd,raw,cmdLen+1);char*av[16]{};int ac=args(cmd,av,16);const char*manifest=nullptr;int optStart=0;if(ac>=3&&seq(av[1],"build")){manifest=av[2];optStart=3;}else if(ac>=2){manifest=av[1];optStart=2;}if(!manifest||!manifest[0]){line("Cheat Wizard Trainer Builder v1.7.3");line("Usage: cw-trainer-builder.exe build trainer.cwtrainer -o MyTrainer.exe");line("   or: cw-trainer-builder.exe trainer.cwtrainer -o MyTrainer.exe");HeapFree(g_heap,0,cmd);ExitProcess(1);}const char*out="Trainer.exe";for(int i=optStart;i<ac;++i){if((seq(av[i],"-o")||seq(av[i],"--output"))&&i+1<ac){out=av[++i];}else{line("Unknown or incomplete option. Use -o <output.exe>.");HeapFree(g_heap,0,cmd);ExitProcess(1);}}line("Cheat Wizard Trainer Builder v1.7.3");bool ok=build(manifest,out);HeapFree(g_heap,0,cmd);ExitProcess(ok?0:2);}
